backend:
  name: github
  repo: Joyce-Peng-GitHub/joyce-blog
  branch: main
  auth_type: pkce
  app_id: Iv23li6tl32WPPchx1JP

media_folder: "images"
public_folder: "/joyce/images"

collections:
  - name: "posts"
    label: "Blog Posts"
    folder: "posts"
    create: true
    extension: "qmd"
    format: "frontmatter"
    slug: "{{year}}-{{month}}-{{day}}-{{uuid_short}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
